title: Time series
url: "https://robinpredict.github.io/"
#baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://robinpredict.github.io/"
footer_text: "Homepage for Ruobin Gao"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "https://robinpredict.github.io/"
 - name: "Resume in Chinese"
   link: "高若滨简历.pdf"
 - name: "Contact"
   link: "contact"
 - name: "Publications"
   link: "publication"
